### ISSUE TITLE
Keen io request url

### ISSUE THREAD

**Issue by job-1994** [krzychb/EspToCloud#2]
Hi, im fairly new to all this. Im trying ot use your Keen io code to publsih some information, however i cant seem to find where to get the request url?

**Comment by krzychb** [comment]
Hi @job-1994,

The  request url looks like at the boom of picture below:
 
![image](https://cloud.githubusercontent.com/assets/12953787/26165857/c2d87c74-3b31-11e7-876b-3973a7656620.png).

Before implementing it for ESP8266, I have first tested how to use it with cURL.
I have followed the Keen.IO's getting started guide - https://keen.io/guides/getting-started/
